# Generated by go2rpm 1.18.0
%bcond check 1

# https://github.com/google/go-containerregistry
%global goipath         github.com/google/go-containerregistry
Version:                0.22.0

%gometa -L -f


Name:           crane
Release:        1
Summary:        Go library and CLIs for working with container registries

# Generated by go-vendor-tools
License:        Apache-2.0 AND BSD-2-Clause AND BSD-3-Clause AND MIT
URL:            %{gourl}
Source0:        %{gosource}
# Generated by go-vendor-tools
Source1:        %{archivename}-vendor.tar.bz2
Source2:        go-vendor-tools.toml

BuildRequires:  go-vendor-tools

%description
Go library and CLIs for working with container registries.

%prep
%goprep -A
%setup -q -T -D -a1 %{forgesetupargs}

%generate_buildrequires
%go_vendor_license_buildrequires -c %{S:2}

%build
export GO_LDFLAGS="-X %{goipath}/cmd/crane/cmd.Version=%{version}"
%global gomodulesmode GO111MODULE=on
%gobuild -o %{gobuilddir}/bin/crane %{goipath}/cmd/crane

%install
%go_vendor_license_install -c %{S:2}
install -m 0755 -vd                     %{buildroot}%{_bindir}
install -m 0755 -vp %{gobuilddir}/bin/* %{buildroot}%{_bindir}/

%check
%go_vendor_license_check -c %{S:2}
%gocheck -d pkg/authn/k8schain -d pkg/authn/kubernetes -d pkg/v1/google

%files -f %{go_vendor_license_filelist}
%license vendor/modules.txt
%doc CONTRIBUTING.md README.md SECURITY.md cmd/crane/doc cmd/crane/README.md
%doc cmd/crane/rebase.md cmd/crane/recipes.md cmd/crane/help/README.md
%doc cmd/gcrane/README.md cmd/ko/README.md cmd/krane/README.md
%doc hack/boilerplate/boilerplate.go.txt pkg/authn/README.md
%doc pkg/authn/k8schain/README.md pkg/legacy/tarball/README.md
%doc pkg/name/README.md pkg/registry/README.md pkg/v1/daemon/README.md
%doc pkg/v1/empty/README.md pkg/v1/google/README.md pkg/v1/layout/README.md
%doc pkg/v1/mutate/README.md pkg/v1/partial/README.md pkg/v1/remote/README.md
%doc pkg/v1/remote/transport/README.md pkg/v1/stream/README.md
%doc pkg/v1/tarball/README.md
%{_bindir}/crane

%changelog
%autochangelog
